Feature/#16272 enhanced messages
clearent/ClearentIdtechIOSFramework pull request #123
Opened 2022-09-08 14:43 UTC by ovidiuurotaru

2022-09-08 15:17 UTC, ovidiuvladpop commented on ClearentIdtechIOSFramework/Wrapper/ClearentExtension.swift
> +            if let filePath = resourceBundle?.path(forResource: "enhancedmessages-v1", ofType: "txt") {
```suggestion
if let filePath = resourceBundle?.path(forResource: "enhancedmessages-v1", ofType: "txt"), let dict = NSDictionary(contentsOfFile: filePath) {
self.enhancedMessagesDict = dict as? [String: String]
}
```

2022-09-08 15:30 UTC, ovidiuvladpop commented on ClearentIdtechIOSFramework/Wrapper/ClearentExtension.swift
> +        }
```suggestion
        if resourceBundle != nil, let filePath = resourceBundle?.path(forResource: "enhancedmessages-v1", ofType: "txt"), let dict = NSDictionary(contentsOfFile: filePath) {
            self.enhancedMessagesDict = dict as? [String:String]
        }
```

2022-09-09 07:26 UTC, carmenj requested changes

2022-09-09 07:26 UTC, carmenj commented on ClearentIdtechIOSFramework/Wrapper/ClearentWrapper.swift
> +    }
`description` property from `UserAction` is identical with the one from `UserInfo`. If we cannot get rid of `UserInfo`,  to avoid duplicate code, you could create a protocol that both `UserAction` & `UserInfo` will adopt. 
Add the implementation of the `description` inside the protocol's extension. Check the example below. The code for `description` was also simplified.
 
```
protocol UserFeedbackProtocol {
    var message: String { get }
    var description: String? { get }
}
extension UserFeedbackProtocol {
    var description: String? {
        if ClearentWrapper.shared.enableEnhancedMessaging && ClearentWrapper.shared.enhancedMessagesDict != nil {
            guard let result = ClearentWrapper.shared.enhancedMessagesDict?[message] else { return nil }
            return result == ClearentConstants.Messaging.suppress ? nil : result
        }
        return message
    }
}
```

2022-09-09 07:26 UTC, carmenj commented on ClearentIdtechIOSFramework/Wrapper/ClearentWrapper.swift
> +        }
```suggestion
        if let action = UserAction.allCases.first(where: { $0.message == text }) {
            return action
        } 
        return text == ClearentConstants.Messaging.suppress ? nil : UserAction(rawValue: text)

```

2022-09-09 07:26 UTC, carmenj commented on ClearentIdtechIOSFramework/Wrapper/ClearentWrapper.swift
> +        }
```suggestion
        if let info = UserInfo.allCases.first(where: { $0.message == text }) {
            return info
        } 
        return text == ClearentConstants.Messaging.suppress ? nil : UserInfo(rawValue: text)
```

2022-09-09 07:26 UTC, carmenj commented on ClearentIdtechIOSFramework/Wrapper/ClearentWrapper.swift
> +        }
```suggestion
        if enableEnhancedMessaging {
            readEnhancedMessages()
        }
```

2022-09-09 07:26 UTC, carmenj commented on ClearentIdtechIOSFramework/Wrapper/ClearentExtension.swift
> +        }
```suggestion
        if let resourceBundle = Bundle(path: path), let filePath = resourceBundle.path(forResource: "enhancedmessages-v1", ofType: "txt"), let dict = NSDictionary(contentsOfFile: filePath) {
            enhancedMessagesDict = dict as? [String: String]
        }
```

2022-09-09 08:08 UTC, carmenj commented on ClearentIdtechIOSFramework/Wrapper/ClearentWrapper.swift
> +        }
```suggestion
        if ClearentWrapper.shared.enableEnhancedMessaging, let dict = ClearentWrapper.shared.enhancedMessagesDict, let result = dict[message] {
            return result == ClearentConstants.Messaging.suppress ? nil : result
        }
        return message
```

2022-09-09 10:35 UTC, carmenj commented on ClearentIdtechIOSFramework/Wrapper/ClearentWrapper.swift
> +         return message
If there is no value in dictionary for the current key, return `message`, not `nil`
```suggestion
        if ClearentWrapper.shared.enableEnhancedMessaging, let dict = ClearentWrapper.shared.enhancedMessagesDict, let result = dict[message] {
            return result == ClearentConstants.Messaging.suppress ? nil : result
        }
        return message
```

2022-09-15 08:09 UTC, merged