Feature/#12895 store forward mode
clearent/ClearentIdtechIOSFramework pull request #128
Opened 2022-10-07 10:46 UTC by ovidiuvladpop

2022-10-07 11:13 UTC, carmenj requested changes

2022-10-07 11:13 UTC, carmenj commented on ClearentIdtechIOSFramework/ClearentUI/ClearentUIManager.swift
> +        clearentWrapper.updateWithInfo(baseURL: baseURL, publicKey: publicKey, apiKey: apiKey, enableEnhancedMessaging: enableEnhancedMessaging, enableOfflineMode: enableOfflineMode)
`enableOfflineMode` is already declared as a global variable which sets the one from `ClearentWrapper`, so I don't think changing this update method is needed.

2022-10-07 11:13 UTC, carmenj commented on ClearentIdtechIOSFramework/ClearentUI/Common/UIComponents/ManualEntryCardInfo/ClearentPaymentHeaderView.swift
> +        if ClearentWrapper.shared.enableOfflineMode && ClearentWrapper.shared.offlineModeState != .off {
ideally, UI components should not have references to `ClearentWrapper`, so you could just pass a  parameter (subtitleText: String?) to a setup function for example.
 If this parameter has a value => insert `ClearentSubtitleLabel`.

2022-10-07 11:13 UTC, carmenj commented on ClearentIdtechIOSFramework/ClearentUI/PaymentFlowDataSource/FlowDataProvider.swift
> +        self.delegate?.didReceiveFlowFeedback(feedback: flowFeedback)
I think `self` keyword is not needed

2022-10-07 11:56 UTC, carmenj commented on ClearentIdtechIOSFramework/ClearentWrapper/Wrapper/ClearentWrapperEnums.swift
> +    case notEncrypted, emvEncryption, msrEncryption, fullyEncrypted
are all these cases used/needed?

2022-10-09 19:53 UTC, ovidiuvladpop commented on ClearentIdtechIOSFramework/ClearentWrapper/Wrapper/ClearentWrapperEnums.swift
> +    case notEncrypted, emvEncryption, msrEncryption, fullyEncrypted
Removed all these cases and compared the response with an int value.

2022-10-09 19:58 UTC, ovidiuvladpop commented on ClearentIdtechIOSFramework/ClearentUI/ClearentProcessingModalPresenter.swift
> +    }
The suggestion from client was to display an error message (not implemented yet).

2022-10-10 10:37 UTC, carmenj commented on ClearentIdtechIOSFramework/ClearentUI/ClearentProcessingModalPresenter.swift
> +    }
please create a separate task for this

2022-10-12 06:54 UTC, merged