Feature/#10100 UI list of readers
clearent/ClearentIdtechIOSFramework pull request #38
Opened 2022-05-26 05:40 UTC by ovidiuvladpop

2022-05-26 12:36 UTC, carmenj requested changes

2022-05-26 12:36 UTC, carmenj commented on ClearentIdtechIOSFramework/ClearentUI/ClearentProcessingModalViewController.swift
> +        showOnTop ? statusHeader.setup(readerName: name, dropDownIconName: ClearentConstants.IconName.expanded, signalStatusIconName: signalStatus.iconName, signalStatusTitle: signalStatus.title, bat
This line is hard to read. Could be simplified like this.
```suggestion
let dropDownIconName = showOnTop ? ClearentConstants.IconName.expanded : nil
statusHeader.setup(readerName: name, dropDownIconName: dropDownIconName, signalStatusIconName: signalStatus.iconName, signalStatusTitle: signalStatus.title, batteryStatusIconName: batteryStatus.iconName, batteryStatusTitle: batteryStatus.title)
```
You can also set fewer parameters to the `setup` method: only `readerName`, `dropDownIconName`, `signalStatus` & `batteryStatus`

2022-05-26 12:36 UTC, carmenj commented on ClearentIdtechIOSFramework/ClearentUI/Common/Assets/Localizable.strings
> +"xsdk_connection_sucessful" = "Connection successful";
successful 😀

2022-05-26 12:36 UTC, carmenj commented on ClearentIdtechIOSFramework/ClearentUI/Common/UIComponents/ClearentReaderStatusHeaderView.swift
> +        UIImage(named: ClearentConstants.IconName.expanded, in: ClearentConstants.bundle, compatibleWith: nil)
```suggestion
        let iconName = state == .collapsed ? ClearentConstants.IconName.collapsed : ClearentConstants.IconName.expanded
        dropDownImageView.image =  UIImage(named: iconName, in: ClearentConstants.bundle, compatibleWith: nil)
```

2022-05-26 12:36 UTC, carmenj commented on ClearentIdtechIOSFramework/ClearentUI/PaymentFlowDataSource/FlowDataProvider.swift
> +            recentlyPairedReaders[indexOfSelectedReader].isConnected = pairedReaderInfo.isConnected
Can these lines be replaced with  `recentlyPairedReaders[indexOfSelectedReader] = pairedReaderInfo`?

2022-05-26 12:36 UTC, carmenj commented on ClearentIdtechIOSFramework/ClearentUI/ClearentProcessingModalViewController.swift
> +            }
```suggestion
    var readersTableViewDataSource: [ReaderItem] = readersInfo.map { ReaderItem(readerInfo: $0) }
```

2022-05-26 12:40 UTC, carmenj commented on ClearentIdtechIOSFramework/ClearentUI/ClearentProcessingModalPresenter.swift
> +    func setSelectedReaderFromReadersList(_ readerItem: ReaderItem?)
couldn't we replace these 2 methods with a single computed property that has a setter and getter?

2022-05-27 07:49 UTC, ovidiuvladpop commented on ClearentIdtechIOSFramework/ClearentUI/ClearentProcessingModalPresenter.swift
> +    func setSelectedReaderFromReadersList(_ readerItem: ReaderItem?)
Updated

2022-05-27 07:50 UTC, ovidiuvladpop commented on ClearentIdtechIOSFramework/ClearentUI/ClearentProcessingModalViewController.swift
> +            }
Updated

2022-05-27 07:53 UTC, ovidiuvladpop commented on ClearentIdtechIOSFramework/ClearentUI/PaymentFlowDataSource/FlowDataProvider.swift
> +            recentlyPairedReaders[indexOfSelectedReader].isConnected = pairedReaderInfo.isConnected
Updated

2022-05-27 09:59 UTC, carmenj approved these changes

2022-05-30 07:45 UTC, carmenj commented on ClearentIdtechIOSFramework/ClearentUI/ClearentProcessingModalViewController.swift
> +        let signalStatus = presenter?.selectedReaderFromReadersList != nil ? readerInfo.signalStatus(flowFeedbackType: flowFeedbackType, isConnecting: true) : readerInfo.signalStatus(flowFeedbackType
```suggestion
        let signalStatus =  readerInfo.signalStatus(flowFeedbackType: flowFeedbackType, isConnecting: presenter?.selectedReaderFromReadersList != nil)
```

2022-05-30 07:47 UTC, carmenj commented on ClearentIdtechIOSFramework/ClearentUI/ClearentProcessingModalPresenter.swift
> +    public var selectedReaderFromReadersList: ReaderItem?
should `selectedReaderFromReadersList` be `public`? maybe `internal` is good enough

2022-05-30 08:51 UTC, merged