Tips functionality part1.
clearent/ClearentIdtechIOSFramework pull request #57
Opened 2022-06-15 12:25 UTC by ovidiuurotaru

2022-06-15 12:31 UTC, ovidiuvladpop commented on ClearentIdtechIOSFramework/ClearentUI/ClearentProcessingModalPresenter.swift
> +        var newAmounts = ClearentConstants.DefaultTipAmounts
You could replace lines between 51-54 with: var newAmounts = tipAmounts ?? ClearentConstants.DefaultTipAmounts

2022-06-15 16:09 UTC, carmenj requested changes

2022-06-16 07:56 UTC, carmenj commented on ClearentIdtechIOSFramework/Wrapper/ClearentWrapper.swift
> +    public func startTransactionWithAmount(amount: String, tip: String?) {
```suggestion
    public func startTransaction(with amount: String, and tip: String?) {
```

2022-06-16 07:56 UTC, carmenj commented on ClearentIdtechIOSFramework/Wrapper/ClearentWrapper.swift
> +    public func startTransactionWithAmount(amount: String, tip: String?) {
```suggestion
    public func startTransaction(with amount: String, and tip: String?) {
```

2022-06-20 07:36 UTC, closed without merging